### ISSUE TITLE
Bulk import zipped folder with IGC files hangs.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#126] opened 2020-10-27 16:14 UTC
If I zip the folder with track logs for a single task and then bulk import these tracks, it hangs:

![Screen Shot 2020-10-27 at 12 11 40 PM](https://user-images.githubusercontent.com/633283/97329715-bc8f7a00-184d-11eb-8e79-5986738b0f86.png)

```python
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by philderbeast** [comment] 2020-11-13 21:19
@kuaka, I tested this today at 7df436ef298f17063e0d8ac13b576719b2bc493e on the development branch. Got the same error.

```
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response.
The function either returned None or ended without a return statement.
```

**Comment by kuaka** [comment] 2020-11-13 21:27
@biuti I noticed that you had made this commit: https://github.com/FAI-CIVL/FAI-Airscore/commit/c630f893792c3be7af1a6a06957647bb0ababfbf
Perhaps this fixes this issue?
Why the code was commented out in the first place?

@biuti Can you please make your bugfixes in a way that they can get into development branch? either in a separate branch that can be merged or directly in development. If we continue to make them in other feature branches it can be a long wait until they find their way into development.

**Comment by biuti** [comment] 2020-11-15 00:21
I made some test, uploading zip files, and it seems to work as intended.
I think we could safely merge in development

**Comment by kuaka** [comment] 2020-11-23 00:16
this is working for me. @philderbeast please test and close if ok,

**Comment by philderbeast** [comment] 2020-11-25 17:14
@kuaka, is it now a requirement to normalise track filenames according to airScores expectations, such as with [fsdb_igc](https://github.com/kuaka/fsdb_igc), before doing a bulk upload of tracks for a task?

**Comment by kuaka** [comment] 2020-11-25 18:13
@philderbeast airScore has always needed some standard format to be able to identify which track belongs to which pilot when uploading in bulk as there is no human making the match. When the bulk upload modal opens there are instructions as to possible formats.
fsdb_igc is only useful when there is a fsdb file which is not normal running for airScore (we normally score comps that are 'live' and not previously scored)

**Closed** 2020-11-29 03:14 UTC
Labels: fsdb, to test
