### ISSUE TITLE
Don't expect the key external_admin_DB to exist.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#180] opened 2020-11-22 11:42 UTC
If I'm using the following `.env` file then please don't expect the key `external_admin_DB` to exist:

```yaml
# .env
use_internal_admin_DB: yes # use internal table for admins and scorekeepers
internal_admin_DB: # if use_internal_admin_DB is yes the below settings are relevant
  allow_self_registration: yes # allows anyone to create a scorekeeper account
```

```yaml
# .env.example
use_internal_admin_DB: yes # use internal table for admins and scorekeepers
internal_admin_DB: # if use_internal_admin_DB is yes the below settings are relevant
  allow_self_registration: yes # allows anyone to create a scorekeeper account
external_admin_DB: # if use_internal_admin_DB is no the below settings are relevant
  auth_url: https://auth_server  # auth server
  auth_type: rest  # rest, ajax, ...
```

```
File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/app/autoapp.py", line 3, in <module>
from airscore.app import create_app
File "/app/airscore/app.py", line 7, in <module>
from airscore import commands, public, user, internal
File "/app/airscore/public/__init__.py", line 3, in <module>
Open an interactive python shell in this framefrom . import views  # noqa
File "/app/airscore/public/views.py", line 16, in <module>
from airscore.public.forms import LoginForm, ModifyParticipantForm, ResetPasswordForm, ResetPasswordRequestForm
File "/app/airscore/public/forms.py", line 5, in <module>
from airscore.user.models import User
File "/app/airscore/user/__init__.py", line 3, in <module>
from . import views  # noqa
File "/app/airscore/user/views.py", line 8, in <module>
import frontendUtils
File "/app/airscore/core/frontendUtils.py", line 1, in <module>
from db.tables import TblCompetition, TblTask, TblCompAuth, TblRegion, TblRegionWaypoint, TblTaskWaypoint
File "/app/airscore/core/db/tables.py", line 6, in <module>
from .conn import db_session
File "/app/airscore/core/db/conn.py", line 14, in <module>
from Defines import MYSQLHOST, DATABASE, MYSQLUSER, MYSQLPASSWORD
File "/app/airscore/core/Defines.py", line 94, in <module>
ADMIN_AUTH_URL = config['external_admin_DB']['auth_url']
KeyError: 'external_admin_DB'
```

**Comment by kuaka** [comment] 2020-11-22 14:57
Both of these keys should always exist and both should be in defines.yaml
and not .env

**Comment by kuaka** [comment] 2020-11-22 18:25
just to be clear: you should not be deleting any keys from the defines.yaml even if they are not applicable. The comments say that they are not relevant but they are still expected.

**Comment by kuaka** [comment] 2020-11-26 07:10
@philderbeast can this be closed?

**Comment by philderbeast** [comment] 2020-11-26 21:39
> Both of these keys should always exist and both should be in defines.yaml and not .env

Yes sorry, config file mixup.

> you should not be deleting any keys from the defines.yaml even if they are not applicable

I don't think I deleted any keys. These files without `.example` suffix are not source controlled.

I'd be happier if the code was robust to missing keys in the config files.

**Comment by kuaka** [comment] 2020-11-26 21:48
> I don't think I deleted any keys. These files without `.example` suffix are not source controlled.

 ok. in the example it has been there for months. I would prefer that the defines.yaml was in source control, but the issue is how can developers make changes to the config and make sure that these changes are not committed or overwritten on a pull.
If you have an answer let us know. I know that there is a way to locally ignore files but have not been able to get it to work.

> I'd be happier if the code was robust to missing keys in the config files.

what do you suggest? in a way the config is like code and I don't think we can expect to have a normal running app that is missing config. I think the only thing could be to make it fail gracefully or to assume defaults if a setting is missing (which could be hard to debug if someone thinks they have set a setting but there is a spelling error and the default is used)

**Comment by kuaka** [comment] 2020-11-29 03:03
I think this should be closed. I don't think it is fair to expect the app to cope with a user deleting configs. In the end, the config is probably only going to be setup once on install and never touched again.

**Closed** 2020-12-13 22:42 UTC
