### ISSUE TITLE
Add default igc parsing config to comps created via import.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#127] opened 2020-10-27 16:19 UTC
If I zip `*.igc` files and bulk import these as tracks for a task, I get the following error:

```python
Traceback (most recent call last):
...
  File "/app/airscore/user/views.py", line 914, in _upload_track_zip
    resp = frontendUtils.process_zip_file(zip_file=zip_file,
  File "/app/airscore/core/frontendUtils.py", line 540, in process_zip_file
    data = process_archive(task, zip_file, check_g_record=grecord, track_source=track_source)
  File "/app/airscore/core/frontendUtils.py", line 521, in process_archive
    assign_and_import_tracks(tracks, task, track_source, check_g_record=check_g_record)
  File "/app/airscore/core/trackUtils.py", line 98, in assign_and_import_tracks
    FlightParsingConfig = igc_parsing_config_from_yaml(task.igc_config_file)
  File "/app/airscore/core/pilot/track.py", line 286, in igc_parsing_config_from_yaml
    if yaml_filename[:-5].lower != '.yaml':
TypeError: 'NoneType' object is not subscriptable
```

**Comment by philderbeast** [comment] 2020-10-27 16:21
I using the [igc files](https://github.com/FlareTiming/2019-dalmatian-score/tree/master/Task%201) from Greda 2019.

**Comment by philderbeast** [comment] 2020-10-27 16:26
If I upload a bare `*.igc` file I take a different route to get the same error:

```python
Traceback (most recent call last):
...
  File "/app/airscore/user/views.py", line 835, in _upload_track
    data, error = frontendUtils.process_igc(taskid, parid, tracklog)
  File "/app/airscore/core/frontendUtils.py", line 319, in process_igc
    FlightParsingConfig = igc_parsing_config_from_yaml(task.igc_config_file)
  File "/app/airscore/core/pilot/track.py", line 286, in igc_parsing_config_from_yaml
    if yaml_filename[:-5].lower != '.yaml':
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kuaka** [comment] 2020-10-27 17:56
OK. you will need to go to compition settings(localhost/users/comp_settings_admin/50) and 'save' this should save the 'standard' igc parsing config file (you can see it as a default in the checks section on that page. looks like there is no default for this parameter when creating a comp via import. There is a default when manually setting up a comp.

**Comment by kuaka** [comment] 2020-10-27 18:16
is this a duplicate of #126 ? likely caused by same problem.

**Comment by biuti** [comment] 2020-11-04 15:18
Looking to fix this.
Is there a reason why, creating or importing a task in competition list page, we are not redirected to comp settings?

**Comment by kuaka** [comment] 2020-11-04 15:51
I'm not exactly sure what competition list is but will assume that you mean users/comp_admin.

As far as I am aware a task cannot be created or imported in this page only a competition. 

This should be a simple fix. Set the default igc parsing config to 'standard' and not null is all that's needed.

Please remember to use a new branch or if it's a simple fix to use development branch so that bug fixes can be merged to development as soon as they are ready. Please don't use another existing branch.

**Comment by biuti** [comment] 2020-11-04 16:15
Sorry I meant, in comp_admin, creating or importing a new comp, it would make sense to be redirected to comp_settings, with a warning that we need to finish setting up all parameters and save.

At the moment after creating a new comp, you remain in comp_admin page.

**Comment by kuaka** [comment] 2020-11-04 16:26
After creating a new comp redirecting to competition settings is a matter of taste and not relevant to this bug.

When creating a new competition it's impossible to process a track if the scorekeeper doesn't go via competition settings. When in competition settings the default standard igc parsing config is set and saved when competition is saved so it's difficult to not have a parsing set and try to process an igc.

The issue is importing a comp. I didn't write the code to import so am not familiar but it seems that the igc parsing config is set to null, furthermore as by importing a comp the other settings and tasks are set it would be common that an igc could be ( attempted to ) processed without pressing save on competition settings page and thereby setting igc config to standard.

All that is needed is a default of standard and not null so that when a competition is imported it is set up correctly for igc processing.

Redirecting is not related to this bug. Even if an import were to be redirected it is not certain that that the user would make a change and therefore hit save, so it would not necessarily solve the problem.

**Comment by kuaka** [comment] 2020-11-04 16:39
Sorry, to answer the original question (even if not related to the bug) there is no important reason that it doesn't redirect after creation (I cannot speak for import) but it was done without redirect so several comps could be setup without unnecessary navigation. (Likely scenario only in testing or if parallel comps are running e.g RTG) . Personaly I think that it's nicer that the user chooses to navigate away from a page than get automatically redirected. Not an important issue either way IMHO

**Comment by biuti** [comment] 2020-11-04 16:47
added standard config to imported comp (https://github.com/FAI-CIVL/FAI-Airscore/commit/d2864fab0fe9cb6d83d29ab3eb9c838185397b00)

**Comment by kuaka** [comment] 2020-11-04 16:53
To add further regarding the choice to redirect or not. The way I see it, in redirecting we are making assumptions about the user's intent. We assume that they want to create and then edit settings. This is likely but not guaranteed. Letting them click on the newly created competition gives them the choice and control. In the airscore UI that I'm familiar with this is consistent across airscore. E.g. when creating a comp the user is not redirected to task admin and can create a second task if needed. 

Re the issue at hand; can this be closed?

**Comment by biuti** [comment] 2020-11-04 17:02
Yes, So if direct redirect is not desirable, I would add a flash warning that comp has been saved but still needs to be setup,, and the same in comp setting, as we have in task setting, a warning that comp setup is not complete yet.
Thoughts?

Yes, we can close this

**Comment by kuaka** [comment] 2020-11-04 17:10
There's nothing that can be done with a competition that's not setup. No
scoring or track upload can happen as no task has been added. So in my
opinion a warning is not needed. A flash message could happen (in green,
not red as it's just info) but any scorekeeper should know that creating a
comp is not enough to have a result.
If you were to add a flash then you would have to reload the page. At the
moment I think we're just reloading the list of comps, the data table with
JS) but I could be wrong.

IMHO there are much bigger priorities....

**Comment by kuaka** [comment] 2020-11-04 17:16
> added standard config to imported comp (https://github.com/FAI-CIVL/FAI-Airscore/commit/d2864fab0fe9cb6d83d29ab3eb9c838185397b00)

I would do this default for all comps not just fsdb imports. So either a default on table field (updating SQL file) or a default on comp object creation.
This then solves the edge case if a comp were to be created and the comp settings page opened to create a task but not saved (if all the default values are desired). Rare but not impossible.

**Comment by biuti** [comment] 2020-11-04 18:22
> I would do this default for all comps not just fsdb imports. So either a default on table field (updating SQL file) or a default on comp object creation.
> This then solves the edge case if a comp were to be created and the comp settings page opened to create a task but not saved (if all the default values are desired). Rare but not impossible.

To work like that, we would need to add default formula, and default values to be stored in forComp table. At the moment formula is Null. That's why I was thinking to redirect to settings after creation.
Otherwise we need a more detailed creation modal in comp_admin.

**Comment by kuaka** [comment] 2020-11-04 18:52
All that needs to happen is when we create (and write to DB) the formula, we have a default for igc_parsing_config. The formula is created when we create a competition : https://github.com/FAI-CIVL/FAI-Airscore/blob/d2864fab0fe9cb6d83d29ab3eb9c838185397b00/airscore/user/views.py#L141

**Comment by biuti** [comment] 2020-11-04 19:42
Yes it is created but is empty, so we miss formula_type and LC calculation.
But I guess a warning flash once comp is saved could make the job.

**Comment by kuaka** [comment] 2020-11-04 19:55
yes it is empty. adding default igc_config will fix **this** issue once and for all but will not fix any bugs from not having a formula_type and LC calc etc. I would not put a warning on competition creation but on competition setting page (on load)  as it is more useful there. (as I say, it is impossible that a competition is created and a scorekeeper uses it without first passing by that page)

**Comment by biuti** [comment] 2020-11-05 15:22
Added default values to Comp object init. (https://github.com/FAI-CIVL/FAI-Airscore/commit/e857fb094d2c4862fb853c06c0ad31a6afc8e7ef)

**Comment by philderbeast** [comment] 2020-11-13 21:31
Whether I save the imported comp or not, at the moment, at 7df436ef298f17063e0d8ac13b576719b2bc493e, I cannot do a bulk import of tracks without hitting an error.

**Comment by kuaka** [comment] 2020-11-23 00:11
This is working for me. @philderbeast can you please test again & close if it's ok.

**Closed** 2020-11-29 03:14 UTC
Labels: fsdb, to test
